language: node_js

node_js:
  - "4"
  - "6"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  matrix:
    - TEST_NPM_VERSION=2
    - TEST_NPM_VERSION=3
    - TEST_NPM_VERSION=4
    # TODO: Add in `yarn` to the matrix.

before_install:
  # Use the requested version of npm
  - npm install -g "npm@$TEST_NPM_VERSION"

script:
  # Check archetype.
  - npm --version
  - npm run builder:check
